version: "3.3"

services:

  feijoadaweek_admin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: feijoadaweek_admin
    hostname: feijoadaweekadmin
    env_file:
      - .env
    environment:
      expose: 8080
    restart: unless-stopped
